name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}}
      - name: Push updated version
        run: |
          npm version patch
          
          git config --global user.name "github_ci"
          git config --global user.email "aliaksandr.kasko.jazzteam@gmail.com"

          git add git add package*.json
          
          git commit -m "Version up [skip ci]"
          git push
    
