name: Version Up

on:
  workflow_call:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  
jobs:
  version-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Patch version
        run: |
          git config --global user.email "aliaksandr.kasko.jazzteam@gmail.com"
          git config --global user.name "github_ci"

          npm version patch

          git add package*.json

          git commit -m "Version up [skip ci]"
          git push
